### ISSUE TITLE
Input shape error

### ISSUE THREAD

**Issue by yitianlian** [ViTAE-Transformer/ViTDet#10]
Hello!I find this error when I run the code?Could you please tell me how to fix it?I guess this problem is at FPN head, but I find no way to fix it.Could you help me?
![image](https://user-images.githubusercontent.com/91449279/170484144-f80c1c40-30a5-4486-b431-b8f4b73627e3.png)

**Comment by Annbless** [comment]
HI,

Could you share the command used for running the code? The information is too limited to find the solutions...

**Comment by yitianlian** [comment]
This is my command:
![image](https://user-images.githubusercontent.com/91449279/170633206-2316641e-22ca-46d9-b4b8-7597e7e13c54.png)
And this is my config files:
![image](https://user-images.githubusercontent.com/91449279/170633269-7dddd1e0-dd56-4d6c-9854-029e658e1796.png)
![image](https://user-images.githubusercontent.com/91449279/170633311-93845c31-3143-4b69-adbd-201101e61ead.png)
![image](https://user-images.githubusercontent.com/91449279/170633349-f4232be1-9d75-43a2-b1f6-8ed0a453fa9d.png)
![image](https://user-images.githubusercontent.com/91449279/170633364-fea4cd49-9aee-4c6d-8f36-84ae97b24543.png)
And my dataset is not coco dataset.I use a thermal image object detection dataset with coco format.

**Comment by yitianlian** [comment]
And I also receive an error today.
![7ce2f176e4a71cc146d53ba5a360ef8](https://user-images.githubusercontent.com/91449279/170633580-a34e6a99-71cc-4ed1-85fa-79a795be1951.png)

**Comment by Annbless** [comment]
We have changed the convolution module's behavior in the rpn, fpn, and head files, which alters the dimensions to adapt to the LN layer. Maybe you forgot to modify that? Since it seems that you integrate some files in the repo to the official mmdetection codebase.

**Comment by yitianlian** [comment]
Oh, I integrate the file into the official mmdetection codbase.That's the reason.Thanks!
