### ISSUE TITLE
Why loading official MAE pretrained model does not match?

### ISSUE THREAD

**Issue by foolhard** [ViTAE-Transformer/ViTDet#18]
I load the offcial MAE pretrained model (_https://dl.fbaipublicfiles.com/mae/pretrain/mae_pretrain_vit_base.pth_) and train VitDet on coco. But found that some keys are missing, 

especially the positioning part. 

Is this an issue or normal thing? Does this impact the accuracy? 

![error](https://user-images.githubusercontent.com/13057970/180144062-6c4ad949-80c4-48ef-aedd-5e7573cd2f78.png)

**Comment by Annbless** [comment]
No.

It is rather normal since these missing parameters are not used in the mae pretraining.

**Comment by foolhard** [comment]
Thanks for quick response.
