### ISSUE TITLE
Why learning rate of ViTDet is much lower (1e-6) than that in setting (1e-4)?

### ISSUE THREAD

**Issue by foolhard** [ViTAE-Transformer/ViTDet#19]
Hi, 

Thanks for your wonderful work.
I try to reproduce your ViTDet on cocodataset by use of default config _'ViTDet-ViT-Base-100e.py'_.

But I found out that the actual learning rate is 1e-6, much lower than the default setting (1e-4). 

**How could I set the learning rate to 1e-4 as defined in setting file?** 

**The actual learning rate** is:
![lr error](https://user-images.githubusercontent.com/13057970/180414889-0eab676e-f073-4edb-8f40-bd3be9a5c189.png)

**The optimizer setting** is as below:

`optimizer = dict(
    type='AdamW',
    lr=0.0001,
    betas=(0.9, 0.999),
    weight_decay=0.1,
    constructor='LayerDecayOptimizerConstructor',
    paramwise_cfg=dict(
        num_layers=12,
        layer_decay_rate=0.7,
        custom_keys=dict(
            bias=dict(decay_multi=0.0),
            pos_embed=dict(decay_mult=0.0),
            relative_position_bias_table=dict(decay_mult=0.0),
            norm=dict(decay_mult=0.0),
            rel_pos_h=dict(decay_mult=0.0),
            rel_pos_w=dict(decay_mult=0.0))))
optimizer_config = dict(grad_clip=None)
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=250,
    warmup_ratio=0.067,
    step=[22, 24])`

**Comment by Annbless** [comment]
Please note that the printed lr is the average lr of all layers. The layer-wise learning rate decay will decay the learning rate for each layer.

**Comment by foolhard** [comment]
Got it. Thanks for quick response.
