### ISSUE TITLE
about lsj_100e config

### ISSUE THREAD

**Issue by youngwanLEE** [ViTAE-Transformer/ViTDet#2]
Hi, 

I'm very impressed by your work! 

I have a question the [lsj_100e config](https://github.com/ViTAE-Transformer/ViTDet/blob/main/configs/ViTDet/lsj_100e_coco_instance_r1024.py#L90).

I'm confused by the epoch number.

In this config, the epoch is set to 25.

https://github.com/ViTAE-Transformer/ViTDet/blob/0d3298c5f30ea63c2cbf89cc74ea8459526f5b0f/configs/ViTDet/lsj_100e_coco_instance_r1024.py#L90

ViTDet is trained for 100 epochs in the paper.

Could you fix me if I'm wrong?

Thanks in advance

**Comment by Annbless** [comment]
Hi,

Please note [this line](https://github.com/ViTAE-Transformer/ViTDet/blob/main/configs/ViTDet/lsj_100e_coco_instance_r1024.py#L62). The COCO dataset has been repeated 4 times to perform the 100 epochs training.

**Comment by youngwanLEE** [comment]
@Annbless 
Oh, I see. 

Thanks for the quick reply :)
