### ISSUE TITLE
Details about MAE pre-trained ViTAE

### ISSUE THREAD

**Issue by Yuxin-CV** [ViTAE-Transformer/ViTDet#4]
Hello and thanks for the awesome work!

I am just curious about how to pre-train a hierarchical ViTAE backbone using MAE, as MAE only encodes visible patches _w/o mask tokens_. Can you provide more details?

Thanks in advance.

**Comment by Annbless** [comment]
Hi,

Thanks for your interest! Please refer to Sec 3.3 and Sec 4.4.1 in the [ViTAEv2](https://arxiv.org/pdf/2202.10108.pdf) paper. We use MAE to train the isotropic design of ViTAE, not the hierarchical ViTAEv2 backbone. We will explore training hierarchical ViTAEv2 backbone using MIM series methods in the future,

**Comment by Yuxin-CV** [comment]
> Hi,
> 
> Thanks for your interest! Please refer to Sec 3.3 and Sec 4.4.1 in the [ViTAEv2](https://arxiv.org/pdf/2202.10108.pdf) paper. We use MAE to train the isotropic design of ViTAE, not the hierarchical ViTAEv2 backbone. We will explore training hierarchical ViTAEv2 backbone using MIM series methods in the future,

Thanks for the prompt response :)

**Comment by Annbless** [comment]
BTW, as pointed out on page 17 of [ViTDet](https://arxiv.org/pdf/2203.16527.pdf), the MAE training of the hierarchical visual transformer can be facilitated by appending mask tokens to the input, which, of course, may slow down the training.

**Comment by Yuxin-CV** [comment]
> BTW, as pointed out on page 17 of [ViTDet](https://arxiv.org/pdf/2203.16527.pdf), the MAE training of the hierarchical visual transformer can be facilitated by appending mask tokens to the input, which, of course, may slow down the training.

Yeah, but I think this approach is more similar to SimMIM than MAE.
