### ISSUE TITLE
Question of PCM

### ISSUE THREAD

**Issue by HerrYu123** [ViTAE-Transformer/ViTDet#5]
Convolutional propagation in the paper is added after each subset. But the PCM is added into every block. Is it Right？

**Comment by Annbless** [comment]
Hello.

The answer is correct, the convolutional propagation in ViTDet is added after each subset of ViT. For ViTAE, PCM is added to each block. We do not add PCM in the ViT model.

In the current implementation, both ViT and ViTAE models use the global attention layer to propagate information. We will add the option of convolutional propagation soon.

**Comment by HerrYu123** [comment]
I got it! Thanks for your quick reply.
