### ISSUE TITLE
Environment Setting

### ISSUE THREAD

**Issue by junchen14** [ViTAE-Transformer/ViTDet#6]
hi, thanks for your wonderful work.
I wanna ask if you have any instruction about the environment setting?

**Comment by Annbless** [comment]
Hi,

We use pytorch with version 1.9.0 for the experiments (NGC version 21.06 is also fine). Besides the usage of docker, we use mmcv-full with version 1.3.9 to construct the environment, i.e.,
```bash
git clone https://github.com/open-mmlab/mmcv.git
cd mmcv
git checkout v1.3.9
MMCV_WITH_OPS=1 pip install -e .
```

Then install this repo, i.e.,
```bash
git clone https://github.com/ViTAE-Transformer/ViTDet.git
cd ViTDet
pip install -v -e .
```

**Comment by junchen14** [comment]
Thanks for your great support! This is very helpful
